version: "3.2"

services:
 nginx:
   image: nginx:alpine
   volumes:
     - .:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
   ports:
     - 81:81
     - 443:443
   depends_on:
     - php

 php:
   build:
     context: .
   volumes:
    - .:/var/www
   ports:
     - 9000:9000
   depends_on:
     - db

 db:
   image: mysql:8
   environment:
     MYSQL_DATABASE: lab_laravel
     MYSQL_ROOT_PASSWORD: root 
   ports:
     - 3307:3306
  
